### PR TITLE
Simplify build

### PR DESCRIPTION
**Pull request by dougmet**
Because I can't cope with Gabor's clever build! Other changes:

* Added knitr suggests for vignettes
* Changed maintainer to me
* Roxygen version bump

### CODE REVIEW

**Comment by gaborcsardi** [comment]
r-builder is deprecated, so :+1:

**Comment by dougmet** [comment]
Would you like to hang on to `cre` (maintainer) or happy for me to take it? I don't mind, probably need to update the email address either way.

**Comment by gaborcsardi** [comment]
If you still use it, then it is better if you take over imo.

**Comment by gaborcsardi** [comment]
Let me know before you submit to CRAN, and I'll email them about the maintainer change.

**Comment by dougmet** [comment]
OK great. WIll do. Thanks!

**Pull request merged**
